### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by 99848873** [kronenthaler/openstep-parser#12]
"/Users/zhoujinyu/Documents/QQCode/mod_project_test/pbxproj/openstep_parser/openstep_parser.py", line 148, in _parse_literal
    key += str[index]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)

when i try to parse a pbxproj file, i got this issue

I find the caseu ,because there are chinese in my file. 
but i don't know how to fix it.

**Comment by XietongLU** [comment]
@99848873 I also encountered the same issue. Do you have a solution?

**Comment by weiss19ja** [comment]
Created a pull request to solve this issue
