### ISSUE TITLE
Exception("Expected { as dictionary start") when used from mod-pbxproj

### ISSUE THREAD

**Issue by yeswecan** [kronenthaler/openstep-parser#23]
Hello there!
The issue arises in the XCode projects generated via openFrameworks (https://github.com/openframeworks/openFrameworks) projectGenerator that generates projects in XML format that it creates by modifying this template: https://github.com/openframeworks/openFrameworks/blob/b674f7ec1f41d8f0fcfea86e3d3d3df3e9bdcf36/scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj

If you open a project in XCode and then save it with some minimal change, it'll open, but without it it'll crash, apparently expecting JSON (?). Would be glad if anyone has anything to tell on this! Thanks.

**Comment by kronenthaler** [comment]
Thank you for report. 

This project is a specialized parser for what it's calle the openstep format, which is indeed a JSON-like format. 

Xcode can interpret both old XML-plist format (what you have) and the new openstep format. This project is not Xcode and only knows how to read the latter.

However, there is an utility tool on macos that allows to transform the XML to the openstep:

```
plutil -convert json <your-file> -o <target-file>
```

This will convert it and allow this library to parse it appropriately.

**Comment by kronenthaler** [comment]
On a second thought. This could be an improvement for the `pbxproj` project. Be able to open other formats, in case of failure of this format.
