### ISSUE TITLE
Comment issue

### ISSUE THREAD

**Issue by Iburidu** [kronenthaler/openstep-parser#5]
Hello,

The current comment condition does not work fine with shell scripts that uses "/bin/sh"
```python
if index + 1 >= len(str) or (str[index] != '/' and str[index + 1] != '*')
```
This exchanges "/bin/sh" to "sh" in shellPath and Xcode fails because of this.

After I changed your code to
```python
if index + 1 >= len(str) or (str[index] != '/' or str[index + 1] != '*')
```
it worked fine. :)

Thanks,
Dani

**Comment by kronenthaler** [comment]
Yes, i saw a fork that did something like it, but that breaks the grammar of the comments established by open step, comments can only be /*. I will check the issue within the strings parsing but some context around would be good to test. Can you post the sanitized project or just the section that is causing the error?

**Comment by Iburidu** [comment]
code example.
/* Begin PBXShellScriptBuildPhase section */
		324A7FB0100CACA900A9A768 /* Strip (shell script) */ = {
			isa = PBXShellScriptBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			inputPaths = (
			);
			name = "Strip (shell script)";
			outputPaths = (
			);
			runOnlyForDeploymentPostprocessing = 0;
			shellPath = /bin/sh;
			shellScript = "/bin/sh ./scripts/strip_executable.sh";
			showEnvVarsInLog = 0;
		};

**Comment by kronenthaler** [comment]
Thanks for the sample, i spotted the issue you where right, changing it from **and** to **or* fixed the condition. I added a unit test for it.
Thanks for the contribution
